// Catálogo de Compras (13/07) — todo o conteúdo do "Grande Catálogo de
// Equipamento" (MERCADO.pdf) estruturado em dados, pra alimentar a aba
// Compras da ficha. Preço é sempre uma faixa (precoMin/precoMax) — a
// tela mostra a média, mas o Mestre/jogador pode negociar dentro da
// faixa (o próprio livro diz isso: "negociado por lojistas").
//
// `espaco` está em "linhas" (mochila = 10 linhas), igual já é usado em
// items.espaco no resto do app — 0.5 = meia linha, 0 = não ocupa
// espaço (usado/vestido, ou item que o livro marca com "———").
//
// Armas têm `meioTransporte` sugerido (coldre/bandoleira/bainha/null)
// baseado na própria descrição do livro (coldre = revólveres,
// bandoleira = fuzil/espingarda, bainha = arma branca) — é só o
// PONTO DE PARTIDA da tentativa automática de equipar ao comprar; se
// não couber no limite, vira item comum na mochila.
export const CATALOGO_COMPRAS = [
  // ---------------------------------------------------------------
  // ARMAS DE FOGO
  // ---------------------------------------------------------------
  {
    id: 'revolver',
    nome: 'Revólver',
    categoria: 'arma_fogo',
    precoMin: 15,
    precoMax: 25,
    espaco: 1,
    descricao: 'Arma mais comum do Oeste Selvagem, carregada em coldre.',
    balas: 6,
    recarga: '2 ações',
    dano: '1 Círculo de Dor',
    tipoDano: null,
    meioTransporte: 'coldre',
  },
  {
    id: 'fuzil',
    nome: 'Fuzil',
    categoria: 'arma_fogo',
    precoMin: 25,
    precoMax: 40,
    espaco: 3,
    descricao: 'Levado em bandoleira. Alcance e dano maiores que o revólver.',
    balas: 5,
    recarga: '2 ações',
    dano: '3 Círculos de Dor',
    tipoDano: null,
    meioTransporte: 'bandoleira',
  },
  {
    id: 'espingarda',
    nome: 'Espingarda',
    categoria: 'arma_fogo',
    precoMin: 25,
    precoMax: 40,
    espaco: 2,
    descricao: 'Dano maior perto, menor de longe. Levada em bandoleira.',
    balas: 2,
    recarga: '1 ação',
    dano: '2 Círculos de Dor (longe) / 2 Círculos de Dor (perto)',
    tipoDano: null,
    meioTransporte: 'bandoleira',
  },
  {
    id: 'garrucha',
    nome: 'Garrucha',
    categoria: 'arma_fogo',
    precoMin: 10,
    precoMax: 20,
    espaco: 1,
    descricao: 'Só funciona bem perto do alvo.',
    balas: 1,
    recarga: '2 ações',
    dano: '2 Círculos de Dor (apenas perto)',
    tipoDano: null,
    meioTransporte: 'coldre',
  },
  {
    id: 'pistola_automatica',
    nome: 'Pistola automática',
    categoria: 'arma_fogo',
    precoMin: 1000,
    precoMax: 2000,
    espaco: 1,
    descricao: 'Protótipo raro — não precisa puxar o cão entre um tiro e outro. Permite tiro adicional por Ação de Combate.',
    balas: 11,
    recarga: '2 ações',
    dano: '1 Círculo de Dor',
    tipoDano: null,
    meioTransporte: 'coldre',
  },
  {
    id: 'magnum_cano_alongado',
    nome: 'Magnum de cano alongado',
    categoria: 'arma_fogo',
    precoMin: 2000,
    precoMax: 4000,
    espaco: 1,
    descricao: 'Calibre .357 — dano devastador.',
    balas: 6,
    recarga: '2 ações',
    dano: '2 Círculos de Dor',
    tipoDano: null,
    meioTransporte: 'coldre',
  },
  {
    id: 'mauser_c69',
    nome: 'Mauser C69',
    categoria: 'arma_fogo',
    precoMin: 2000,
    precoMax: 4000,
    espaco: 1,
    descricao: 'Carregador grande, calibre 7.63mm.',
    balas: 15,
    recarga: '1 ação',
    dano: '1 Círculo de Dor',
    tipoDano: null,
    meioTransporte: 'coldre',
  },
  {
    id: 'carabina_repeticao',
    nome: 'Carabina de repetição',
    categoria: 'arma_fogo',
    precoMin: 1000,
    precoMax: 2000,
    espaco: 2,
    descricao: 'Tiro adicional na primeira Ação de Combate do turno, com penalidade -1 nos Testes de Violência.',
    balas: 7,
    recarga: '2 ações',
    dano: '2 Círculos de Dor',
    tipoDano: null,
    meioTransporte: 'bandoleira',
  },
  {
    id: 'derringer',
    nome: 'Derringer (revólver escondido)',
    categoria: 'arma_fogo',
    precoMin: 300,
    precoMax: 300,
    espaco: 1,
    descricao: 'Discreta — presa à manga por uma esteira de molas. Aproveita bônus da Habilidade Ataque Sacana.',
    balas: 2,
    recarga: '1 ação',
    dano: '1 Círculo de Dor',
    tipoDano: null,
    meioTransporte: 'coldre',
  },
  {
    id: 'espingarda_cano_serrado',
    nome: 'Espingarda de cano serrado',
    categoria: 'arma_fogo',
    precoMin: 50,
    precoMax: 150,
    espaco: 2,
    descricao: 'Alcance reduzido, dano maior. Pequena o bastante pro coldre da cintura.',
    balas: 2,
    recarga: '2 ações',
    dano: '3 Círculos de Dor',
    tipoDano: null,
    meioTransporte: 'coldre',
  },
  {
    id: 'canhao_cavalaria',
    nome: 'Canhão de cavalaria',
    categoria: 'arma_fogo',
    precoMin: null,
    precoMax: null,
    espaco: 0,
    descricao: 'Não se vende. Atinge área de 3m de raio; NA 7 de Violência em vez de Defesa do alvo.',
    balas: 1,
    recarga: '2 turnos',
    dano: '6 Círculos de Dor',
    tipoDano: null,
    meioTransporte: null,
  },
  {
    id: 'metralhadora_montada',
    nome: 'Metralhadora montada',
    categoria: 'arma_fogo',
    precoMin: null,
    precoMax: null,
    espaco: 0,
    descricao: 'Não se vende. Atinge todos os alvos em linha; 3 de Vida por Ação de Combate + Movimento gastos.',
    balas: null,
    recarga: '2 turnos',
    dano: '3 Círculos de Vida por ação/movimento gasto',
    tipoDano: 'vida',
    meioTransporte: null,
  },
  {
    id: 'explosivos',
    nome: 'Explosivos (TNT/Dinamite)',
    categoria: 'arma_fogo',
    precoMin: 30,
    precoMax: 40,
    espaco: 0.5,
    descricao: 'Área de 1,5m de raio. Tirou 1 no Teste de Violência: Resistência de Velocidade ou explode na mão.',
    balas: null,
    recarga: '3 ações',
    dano: '5 Círculos de Dor',
    tipoDano: null,
    meioTransporte: null,
  },

  // ---------------------------------------------------------------
  // ARMAS BRANCAS
  // ---------------------------------------------------------------
  {
    id: 'zarabatana',
    nome: 'Zarabatana',
    categoria: 'arma_branca',
    precoMin: 3,
    precoMax: 10,
    espaco: 1,
    descricao: 'Dano acompanhado de veneno.',
    balas: null,
    recarga: null,
    dano: '1 Círculo de Dor + veneno',
    tipoDano: null,
    meioTransporte: null,
  },
  {
    id: 'estilingue',
    nome: 'Estilingue',
    categoria: 'arma_branca',
    precoMin: 1,
    precoMax: 5,
    espaco: 1,
    descricao: '',
    balas: null,
    recarga: null,
    dano: '2 Círculos de Dor',
    tipoDano: null,
    meioTransporte: null,
  },
  {
    id: 'boleadeira',
    nome: 'Boleadeira',
    categoria: 'arma_branca',
    precoMin: 1,
    precoMax: 1,
    espaco: 1,
    descricao: '',
    balas: null,
    recarga: null,
    dano: '3 Círculos de Dor',
    tipoDano: null,
    meioTransporte: null,
  },
  {
    id: 'arco_flecha',
    nome: 'Arco e flecha',
    categoria: 'arma_branca',
    precoMin: 25,
    precoMax: 25,
    espaco: 1,
    descricao: '',
    balas: null,
    recarga: null,
    dano: '1 Círculo de Dor',
    tipoDano: null,
    meioTransporte: null,
  },
  {
    id: 'faca',
    nome: 'Faca',
    categoria: 'arma_branca',
    precoMin: 1,
    precoMax: 5,
    espaco: 0,
    descricao: 'Levada em bainha — não ocupa espaço na mochila.',
    balas: null,
    recarga: null,
    dano: '3 Círculos de Dor',
    tipoDano: null,
    meioTransporte: 'bainha',
  },
  {
    id: 'sabre',
    nome: 'Sabre (Espada)',
    categoria: 'arma_branca',
    precoMin: 5,
    precoMax: 25,
    espaco: 0,
    descricao: 'Levada em bainha — não ocupa espaço na mochila.',
    balas: null,
    recarga: null,
    dano: '1 Círculo de Dor',
    tipoDano: null,
    meioTransporte: 'bainha',
  },
  {
    id: 'lanca',
    nome: 'Lança',
    categoria: 'arma_branca',
    precoMin: 15,
    precoMax: 25,
    espaco: 2,
    descricao: 'Grande demais pra bainha ou coldre.',
    balas: null,
    recarga: null,
    dano: '1 Círculo de Dor',
    tipoDano: null,
    meioTransporte: null,
  },
  {
    id: 'machadinha',
    nome: 'Machadinha',
    categoria: 'arma_branca',
    precoMin: 5,
    precoMax: 10,
    espaco: 1,
    descricao: '',
    balas: null,
    recarga: null,
    dano: '2 Círculos de Dor',
    tipoDano: null,
    meioTransporte: 'bainha',
  },
  {
    id: 'machado_lenha',
    nome: 'Machado de lenha',
    categoria: 'arma_branca',
    precoMin: 1,
    precoMax: 2,
    espaco: 2,
    descricao: '',
    balas: null,
    recarga: null,
    dano: '2 Círculos de Dor',
    tipoDano: null,
    meioTransporte: null,
  },
  {
    id: 'martelo_mao',
    nome: 'Martelo de mão',
    categoria: 'arma_branca',
    precoMin: 5,
    precoMax: 10,
    espaco: 1,
    descricao: '',
    balas: null,
    recarga: null,
    dano: '1 Círculo de Dor',
    tipoDano: null,
    meioTransporte: null,
  },

  // ---------------------------------------------------------------
  // ACESSÓRIOS E MUNIÇÃO
  // ---------------------------------------------------------------
  {
    id: 'bainha',
    nome: 'Bainha',
    categoria: 'acessorio',
    precoMin: 3,
    precoMax: 10,
    espaco: 0,
    descricao: 'Carrega uma faca, espada ou arma branca equivalente. Não ocupa espaço na mochila. É só flavor/reposição — comprar não muda o limite de armas equipadas (esse limite é fixo do personagem, veja "Detalhes" na tabela de Armas).',
  },
  {
    id: 'bandoleira',
    nome: 'Bandoleira',
    categoria: 'acessorio',
    precoMin: 5,
    precoMax: 20,
    espaco: 0,
    descricao: 'Carrega um fuzil ou espingarda e até 24 balas dessas armas. Não ocupa espaço na mochila. É só flavor/reposição — comprar não muda o limite de armas equipadas (esse limite é fixo do personagem, veja "Detalhes" na tabela de Armas).',
  },
  {
    id: 'coldre',
    nome: 'Coldre',
    categoria: 'acessorio',
    precoMin: 4,
    precoMax: 15,
    espaco: 0,
    descricao: 'Carrega um revólver ou arma semelhante e até 36 balas de revólver. Não ocupa espaço na mochila. É só flavor/reposição — comprar não muda o limite de armas equipadas (esse limite é fixo do personagem, veja "Detalhes" na tabela de Armas).',
  },
  {
    id: 'municao_revolver',
    nome: 'Munição de revólver (caixa com 12 balas)',
    categoria: 'municao',
    precoMin: 3,
    precoMax: 8,
    espaco: 1,
    descricao: 'Abastece a reserva de munição leve (coldre). 12 balas por caixa.',
    quantidadePorCompra: 12,
    poolAlvo: 'leve',
  },
  {
    id: 'municao_espingarda',
    nome: 'Munição de espingarda (caixa com 6 balas)',
    categoria: 'municao',
    precoMin: 7,
    precoMax: 10,
    espaco: 1,
    descricao: 'Abastece a reserva de munição pesada (bandoleira). 6 balas por caixa.',
    quantidadePorCompra: 6,
    poolAlvo: 'pesada',
  },
  {
    id: 'municao_fuzil',
    nome: 'Munição de fuzil (caixa com 6 balas)',
    categoria: 'municao',
    precoMin: 6,
    precoMax: 12,
    espaco: 1,
    descricao: 'Abastece a reserva de munição pesada (bandoleira). 6 balas por caixa.',
    quantidadePorCompra: 6,
    poolAlvo: 'pesada',
  },

  // ---------------------------------------------------------------
  // PROTEÇÃO
  // ---------------------------------------------------------------
  {
    id: 'sobretudo_protecao',
    nome: 'Sobretudo (proteção)',
    categoria: 'protecao',
    precoMin: 50,
    precoMax: 70,
    espaco: 0.5,
    descricao: 'Penalidade: -1 Ação de Combate (mín. 1). Não reduz dano de explosão, só tiro/corpo a corpo.',
    reducaoDano: 1,
    limiteDano: 2,
  },
  {
    id: 'colete_couro_reforcado',
    nome: 'Colete de couro reforçado',
    categoria: 'protecao',
    precoMin: 100,
    precoMax: 200,
    espaco: 0.5,
    descricao: 'Penalidade: -1 Movimento (mín. 1). Não reduz dano de explosão, só tiro/corpo a corpo.',
    reducaoDano: 1,
    limiteDano: 3,
  },
  {
    id: 'colete_couro_madeira',
    nome: 'Colete de couro com madeira',
    categoria: 'protecao',
    precoMin: 150,
    precoMax: 250,
    espaco: 1,
    descricao: 'Penalidade: -1 Ação de Combate e -1 Movimento (mín. 1 cada). Não reduz dano de explosão.',
    reducaoDano: 2,
    limiteDano: 4,
  },
  {
    id: 'ombreiras_ferro',
    nome: 'Ombreiras de ferro',
    categoria: 'protecao',
    precoMin: 400,
    precoMax: 500,
    espaco: 1,
    descricao: 'Penalidade: -2 Movimentos (mín. 1). Não reduz dano de explosão.',
    reducaoDano: 2,
    limiteDano: 4,
  },
  {
    id: 'placas_metal',
    nome: 'Placas de metal',
    categoria: 'protecao',
    precoMin: 100,
    precoMax: 400,
    espaco: 1.5,
    descricao: 'Penalidade: -2 Movimentos e -1 Ação de Combate (mín. 1 cada). Não reduz dano de explosão.',
    reducaoDano: 3,
    limiteDano: 5,
  },
  {
    id: 'panelas_chumbadas',
    nome: 'Panelas chumbadas',
    categoria: 'protecao',
    precoMin: 200,
    precoMax: 400,
    espaco: 1.5,
    descricao: 'Penalidade: -1 Movimento e -2 Ações de Combate (mín. 1 cada). Não reduz dano de explosão.',
    reducaoDano: 3,
    limiteDano: 4,
  },

  // ---------------------------------------------------------------
  // MERCEARIA DA ALEGRIA (comida e afins)
  // ---------------------------------------------------------------
  { id: 'acucar', nome: 'Açúcar (½ kg)', categoria: 'comida', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },
  { id: 'alcacuz', nome: 'Alcaçuz (doces)', categoria: 'comida', precoMin: 0.5, precoMax: 1, espaco: 0, descricao: '' },
  { id: 'atum', nome: 'Atum (lata)', categoria: 'comida', precoMin: 0.1, precoMax: 0.5, espaco: 0.5, descricao: '' },
  { id: 'azeite', nome: 'Azeite (garrafa)', categoria: 'comida', precoMin: 2, precoMax: 2, espaco: 1, descricao: '' },
  { id: 'biscoitos', nome: 'Biscoitos', categoria: 'comida', precoMin: 0.5, precoMax: 1, espaco: 0, descricao: '' },
  { id: 'carne_seca', nome: 'Carne Seca (1kg)', categoria: 'comida', precoMin: 1, precoMax: 2, espaco: 1, descricao: '' },
  { id: 'cafe', nome: 'Café (lata)', categoria: 'comida', precoMin: 0.5, precoMax: 1, espaco: 0, descricao: 'Máximo 3 latas na mochila.', maximoPorPersonagem: 3 },
  { id: 'cenouras', nome: 'Cenouras (5)', categoria: 'comida', precoMin: 0.05, precoMax: 0.25, espaco: 1, descricao: '' },
  { id: 'cerveja', nome: 'Cerveja (garrafa)', categoria: 'comida', precoMin: 0.25, precoMax: 1, espaco: 1, descricao: '' },
  { id: 'chocolate', nome: 'Chocolate (barra)', categoria: 'comida', precoMin: 1, precoMax: 4, espaco: 0, descricao: '' },
  { id: 'conhaque', nome: 'Conhaque fino (garrafa)', categoria: 'comida', precoMin: 40, precoMax: 60, espaco: 0.5, descricao: '' },
  { id: 'ervilhas', nome: 'Ervilhas (lata)', categoria: 'comida', precoMin: 3, precoMax: 15, espaco: 0.5, descricao: '' },
  { id: 'erva_medicinal', nome: 'Erva medicinal (½ kg)', categoria: 'comida', precoMin: 5, precoMax: 50, espaco: 0.5, descricao: '' },
  { id: 'farinha', nome: 'Farinha (½ kg)', categoria: 'comida', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },
  { id: 'feijao', nome: 'Feijão (Lata)', categoria: 'comida', precoMin: 0.5, precoMax: 2, espaco: 1, descricao: '' },
  { id: 'folhas_cha', nome: 'Folhas de chá (½ kg)', categoria: 'comida', precoMin: 1, precoMax: 2, espaco: 1, descricao: '' },
  { id: 'leite', nome: 'Leite (½ litro)', categoria: 'comida', precoMin: 3, precoMax: 5, espaco: 1, descricao: '' },
  { id: 'maca', nome: 'Maçã (3)', categoria: 'comida', precoMin: 0.1, precoMax: 0.1, espaco: 0, descricao: '' },
  { id: 'milho', nome: 'Milho (lata)', categoria: 'comida', precoMin: 0.1, precoMax: 0.5, espaco: 0.5, descricao: '' },
  { id: 'ovos', nome: 'Ovos (6)', categoria: 'comida', precoMin: 1, precoMax: 2.5, espaco: 0.5, descricao: '' },
  { id: 'paierinho', nome: 'Paierinho (5)', categoria: 'comida', precoMin: 0.5, precoMax: 1, espaco: 0, descricao: '' },
  { id: 'pinga', nome: 'Pinga (garrafa)', categoria: 'comida', precoMin: 0.25, precoMax: 1, espaco: 1, descricao: '' },
  { id: 'pao_queijo', nome: 'Pão de queijo (10)', categoria: 'comida', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },
  { id: 'sardinha', nome: 'Sardinha (lata)', categoria: 'comida', precoMin: 0.1, precoMax: 0.25, espaco: 0.5, descricao: '' },
  { id: 'sopa', nome: 'Sopa', categoria: 'comida', precoMin: 0.5, precoMax: 2, espaco: 1, descricao: '' },
  { id: 'queijo', nome: 'Queijo (½ Kg)', categoria: 'comida', precoMin: 3, precoMax: 6, espaco: 0.5, descricao: '' },
  { id: 'tabaco', nome: 'Tabaco (½ Kg)', categoria: 'comida', precoMin: 2, precoMax: 5, espaco: 0.5, descricao: '' },
  { id: 'tonico_capilar', nome: 'Tônico capilar (frasco)', categoria: 'comida', precoMin: 10, precoMax: 15, espaco: 0.5, descricao: '' },
  { id: 'vinho', nome: 'Vinho (garrafa)', categoria: 'comida', precoMin: 5, precoMax: 10, espaco: 1, descricao: '' },
  { id: 'unguento', nome: 'Unguento (frasco)', categoria: 'comida', precoMin: 5, precoMax: 10, espaco: 1, descricao: 'Cura 1 Círculo de Vida ao ser aplicado durante o descanso.' },
  { id: 'uisque', nome: 'Uísque (garrafa)', categoria: 'comida', precoMin: 5, precoMax: 10, espaco: 1, descricao: '' },
  { id: 'sabao_mercearia', nome: 'Sabão (barra)', categoria: 'comida', precoMin: 0.1, precoMax: 0.25, espaco: 0, descricao: '' },
  { id: 'fosforos', nome: 'Fósforos (10)', categoria: 'comida', precoMin: 0.05, precoMax: 0.1, espaco: 0, descricao: '' },
  { id: 'jornal', nome: 'Jornal', categoria: 'comida', precoMin: 0.25, precoMax: 0.25, espaco: 0, descricao: '' },
  { id: 'martelo_mercearia', nome: 'Martelo', categoria: 'comida', precoMin: 0.5, precoMax: 1, espaco: 1, descricao: '' },
  { id: 'mochila_item', nome: 'Mochila', categoria: 'comida', precoMin: 1, precoMax: 1, espaco: 0, descricao: '' },
  { id: 'oleo_lanterna', nome: 'Óleo (lanterna)', categoria: 'comida', precoMin: 0.25, precoMax: 0.5, espaco: 0.5, descricao: '' },
  { id: 'tabua_lavar', nome: 'Tábua de lavar', categoria: 'comida', precoMin: 1, precoMax: 3, espaco: 1, descricao: '' },
  { id: 'camera_photographyca', nome: 'Câmera Photographyca', categoria: 'comida', precoMin: 3000, precoMax: 3000, espaco: 2, descricao: 'Novidade direto do Estrangeiro.' },

  // ---------------------------------------------------------------
  // RODA DA MODA (roupas e acessórios de moda)
  // ---------------------------------------------------------------
  { id: 'anel', nome: 'Anel (latão - diamante)', categoria: 'roupa', precoMin: 1, precoMax: 1500, espaco: 0, descricao: 'Roupas/acessórios vestidos não ocupam espaço na mochila.' },
  { id: 'avental_medico', nome: 'Avental de médico', categoria: 'roupa', precoMin: 2, precoMax: 5, espaco: 0.5, descricao: '' },
  { id: 'batina', nome: 'Batina', categoria: 'roupa', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },
  { id: 'bengala', nome: 'Bengala', categoria: 'roupa', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },
  { id: 'boina', nome: 'Boina', categoria: 'roupa', precoMin: 0.5, precoMax: 1, espaco: 0.5, descricao: '' },
  { id: 'bolsa_mao', nome: 'Bolsa de mão', categoria: 'roupa', precoMin: 10, precoMax: 20, espaco: 0.5, descricao: '' },
  { id: 'botas', nome: 'Botas', categoria: 'roupa', precoMin: 5, precoMax: 10, espaco: 0.5, descricao: '' },
  { id: 'blusa_inverno', nome: 'Blusa de inverno', categoria: 'roupa', precoMin: 10, precoMax: 30, espaco: 0.5, descricao: '' },
  { id: 'blusa_verao', nome: 'Blusa de verão', categoria: 'roupa', precoMin: 1, precoMax: 5, espaco: 0.5, descricao: '' },
  { id: 'brincos', nome: 'Brincos (latão - diamantes)', categoria: 'roupa', precoMin: 5, precoMax: 1500, espaco: 0, descricao: '' },
  { id: 'broche', nome: 'Broche (latão - prata)', categoria: 'roupa', precoMin: 2, precoMax: 500, espaco: 0, descricao: '' },
  { id: 'calca', nome: 'Calça', categoria: 'roupa', precoMin: 2, precoMax: 8, espaco: 0.5, descricao: '' },
  { id: 'camisa', nome: 'Camisa', categoria: 'roupa', precoMin: 2, precoMax: 5, espaco: 0.5, descricao: '' },
  { id: 'camisola', nome: 'Camisola', categoria: 'roupa', precoMin: 10, precoMax: 25, espaco: 0.5, descricao: '' },
  { id: 'cartola', nome: 'Cartola', categoria: 'roupa', precoMin: 15, precoMax: 20, espaco: 0.5, descricao: '' },
  { id: 'casaco', nome: 'Casaco', categoria: 'roupa', precoMin: 2, precoMax: 15, espaco: 0.5, descricao: '' },
  { id: 'ceroulas', nome: 'Ceroulas', categoria: 'roupa', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },
  { id: 'chapeu', nome: 'Chapéu', categoria: 'roupa', precoMin: 5, precoMax: 100, espaco: 0.5, descricao: '' },
  { id: 'cinto', nome: 'Cinto', categoria: 'roupa', precoMin: 1, precoMax: 5, espaco: 0.5, descricao: '' },
  { id: 'colar', nome: 'Colar (ferro - pérolas)', categoria: 'roupa', precoMin: 2, precoMax: 2500, espaco: 0, descricao: '' },
  { id: 'colete_moda', nome: 'Colete', categoria: 'roupa', precoMin: 3, precoMax: 15, espaco: 0.5, descricao: '' },
  { id: 'echarpe', nome: 'Echarpe', categoria: 'roupa', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },
  { id: 'estetoscopio', nome: 'Estetoscópio', categoria: 'roupa', precoMin: 10, precoMax: 50, espaco: 0.5, descricao: '' },
  { id: 'lenco_pescoco', nome: 'Lenço de pescoço', categoria: 'roupa', precoMin: 0.5, precoMax: 1, espaco: 0.5, descricao: '' },
  { id: 'leque', nome: 'Leque', categoria: 'roupa', precoMin: 1, precoMax: 3, espaco: 0.5, descricao: '' },
  { id: 'lingerie', nome: 'Lingerie', categoria: 'roupa', precoMin: 3, precoMax: 100, espaco: 0.5, descricao: '' },
  { id: 'luvas', nome: 'Luvas', categoria: 'roupa', precoMin: 0.25, precoMax: 1, espaco: 0.5, descricao: '' },
  { id: 'gargantilha', nome: 'Gargantilha', categoria: 'roupa', precoMin: 0.5, precoMax: 1, espaco: 0.5, descricao: '' },
  { id: 'gravata', nome: 'Gravata', categoria: 'roupa', precoMin: 1, precoMax: 5, espaco: 0.5, descricao: '' },
  { id: 'jaqueta', nome: 'Jaqueta', categoria: 'roupa', precoMin: 10, precoMax: 300, espaco: 0.5, descricao: '' },
  { id: 'oculos_moda', nome: 'Óculos', categoria: 'roupa', precoMin: 5, precoMax: 25, espaco: 0.5, descricao: '' },
  { id: 'macacao_jeans', nome: 'Macacão jeans', categoria: 'roupa', precoMin: 0.5, precoMax: 3, espaco: 0.5, descricao: '' },
  { id: 'meias', nome: 'Meias', categoria: 'roupa', precoMin: 0.1, precoMax: 0.25, espaco: 0.5, descricao: '' },
  { id: 'paleto', nome: 'Paletó', categoria: 'roupa', precoMin: 20, precoMax: 50, espaco: 0.5, descricao: '' },
  { id: 'perneiras', nome: 'Perneiras', categoria: 'roupa', precoMin: 10, precoMax: 15, espaco: 0.5, descricao: '' },
  { id: 'pijamas', nome: 'Pijamas', categoria: 'roupa', precoMin: 1, precoMax: 30, espaco: 0.5, descricao: '' },
  { id: 'poncho', nome: 'Poncho', categoria: 'roupa', precoMin: 1, precoMax: 50, espaco: 0.5, descricao: '' },
  { id: 'pulseira', nome: 'Pulseira (lata - diamante)', categoria: 'roupa', precoMin: 2, precoMax: 2000, espaco: 0, descricao: '' },
  { id: 'saia', nome: 'Saia', categoria: 'roupa', precoMin: 1, precoMax: 15, espaco: 0.5, descricao: '' },
  { id: 'sapatos', nome: 'Sapatos', categoria: 'roupa', precoMin: 2, precoMax: 100, espaco: 0.5, descricao: '' },
  { id: 'sobretudo_moda', nome: 'Sobretudo (moda)', categoria: 'roupa', precoMin: 10, precoMax: 200, espaco: 0.5, descricao: 'Versão sem função de proteção — só moda. Pra usar como proteção, veja "Sobretudo (proteção)".' },
  { id: 'sombrero', nome: 'Sombrero', categoria: 'roupa', precoMin: 5, precoMax: 20, espaco: 0.5, descricao: '' },
  { id: 'suspensorios', nome: 'Suspensórios', categoria: 'roupa', precoMin: 1, precoMax: 5, espaco: 0.5, descricao: '' },
  { id: 'vestido', nome: 'Vestido (trabalho - gala)', categoria: 'roupa', precoMin: 2, precoMax: 150, espaco: 0.5, descricao: '' },
  { id: 'tuxedo', nome: 'Tuxedo', categoria: 'roupa', precoMin: 10, precoMax: 50, espaco: 0.5, descricao: '' },
  { id: 'xale_la', nome: 'Xale de lã', categoria: 'roupa', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },

  // ---------------------------------------------------------------
  // VÁRIOS TREM DE ARMAZÉM (ferramentas e diversos)
  // ---------------------------------------------------------------
  { id: 'acordeao', nome: 'Acordeão (sanfona)', categoria: 'ferramenta', precoMin: 30, precoMax: 50, espaco: 1, descricao: '' },
  { id: 'alicate_arame', nome: 'Alicate de arame', categoria: 'ferramenta', precoMin: 20, precoMax: 50, espaco: 1, descricao: '' },
  { id: 'algemas', nome: 'Algemas', categoria: 'ferramenta', precoMin: 2, precoMax: 4, espaco: 0.5, descricao: '' },
  { id: 'arame', nome: 'Arame (10m)', categoria: 'ferramenta', precoMin: 3, precoMax: 5, espaco: 2, descricao: '' },
  { id: 'banjo', nome: 'Banjo', categoria: 'ferramenta', precoMin: 50, precoMax: 100, espaco: 1, descricao: '' },
  { id: 'baralho', nome: 'Baralho', categoria: 'ferramenta', precoMin: 0.5, precoMax: 2, espaco: 0, descricao: '' },
  { id: 'barraca', nome: 'Barraca', categoria: 'ferramenta', precoMin: 7, precoMax: 12, espaco: 1, descricao: '' },
  { id: 'berimbau', nome: 'Berimbau', categoria: 'ferramenta', precoMin: 1, precoMax: 2, espaco: 1, descricao: '' },
  { id: 'binoculo', nome: 'Binóculo', categoria: 'ferramenta', precoMin: 25, precoMax: 40, espaco: 0.5, descricao: '' },
  { id: 'brinquedo', nome: 'Brinquedo', categoria: 'ferramenta', precoMin: 10, precoMax: 20, espaco: 0.5, descricao: '' },
  { id: 'bussola', nome: 'Bússola', categoria: 'ferramenta', precoMin: 1, precoMax: 5, espaco: 0, descricao: '' },
  { id: 'cadeado', nome: 'Cadeado', categoria: 'ferramenta', precoMin: 0.5, precoMax: 1, espaco: 0.5, descricao: '' },
  { id: 'cantil', nome: 'Cantil', categoria: 'ferramenta', precoMin: 3, precoMax: 5, espaco: 0, descricao: '' },
  { id: 'corrente', nome: 'Corrente (2m)', categoria: 'ferramenta', precoMin: 10, precoMax: 25, espaco: 1, descricao: '' },
  { id: 'corda', nome: 'Corda (5m)', categoria: 'ferramenta', precoMin: 1, precoMax: 5, espaco: 1, descricao: '' },
  { id: 'dados', nome: 'Dados (3)', categoria: 'ferramenta', precoMin: 0.5, precoMax: 1, espaco: 0, descricao: '' },
  { id: 'detonador', nome: 'Detonador', categoria: 'ferramenta', precoMin: 3, precoMax: 5, espaco: 1, descricao: '' },
  { id: 'foice', nome: 'Foice', categoria: 'ferramenta', precoMin: 10, precoMax: 25, espaco: 1, descricao: '' },
  { id: 'forcado', nome: 'Forcado', categoria: 'ferramenta', precoMin: 10, precoMax: 25, espaco: 1, descricao: '' },
  { id: 'flauta', nome: 'Flauta', categoria: 'ferramenta', precoMin: 2, precoMax: 100, espaco: 1, descricao: '' },
  { id: 'gaita', nome: 'Gaita (Harmônica)', categoria: 'ferramenta', precoMin: 15, precoMax: 25, espaco: 1, descricao: '' },
  { id: 'ganza', nome: 'Ganzá (Chocalho)', categoria: 'ferramenta', precoMin: 5, precoMax: 10, espaco: 1, descricao: '' },
  { id: 'gazuas', nome: 'Gazuas (20)', categoria: 'ferramenta', precoMin: 0.5, precoMax: 1, espaco: 1, descricao: '' },
  { id: 'graxa', nome: 'Graxa (pote)', categoria: 'ferramenta', precoMin: 1, precoMax: 2, espaco: 0.5, descricao: '' },
  { id: 'isqueiro', nome: 'Isqueiro', categoria: 'ferramenta', precoMin: 5, precoMax: 30, espaco: 0, descricao: '' },
  { id: 'lanterna', nome: 'Lanterna', categoria: 'ferramenta', precoMin: 5, precoMax: 10, espaco: 1, descricao: '' },
  { id: 'linha_agulha', nome: 'Linha e agulha', categoria: 'ferramenta', precoMin: 0.5, precoMax: 1, espaco: 0, descricao: '' },
  { id: 'lona', nome: 'Lona (2m)', categoria: 'ferramenta', precoMin: 20, precoMax: 30, espaco: 2, descricao: '' },
  { id: 'machado_ferramenta', nome: 'Machado', categoria: 'ferramenta', precoMin: 10, precoMax: 25, espaco: 1, descricao: '' },
  { id: 'marreta', nome: 'Marreta', categoria: 'ferramenta', precoMin: 10, precoMax: 25, espaco: 1, descricao: '' },
  { id: 'oculos_ferramenta', nome: 'Óculos (proteção)', categoria: 'ferramenta', precoMin: 20, precoMax: 50, espaco: 0.5, descricao: '' },
  { id: 'oleo_lata', nome: 'Óleo (lata)', categoria: 'ferramenta', precoMin: 1, precoMax: 2, espaco: 1, descricao: '' },
  { id: 'pa', nome: 'Pá', categoria: 'ferramenta', precoMin: 1, precoMax: 2, espaco: 1, descricao: '' },
  { id: 'pandeiro', nome: 'Pandeiro', categoria: 'ferramenta', precoMin: 60, precoMax: 80, espaco: 1, descricao: '' },
  { id: 'panela', nome: 'Panela', categoria: 'ferramenta', precoMin: 3, precoMax: 10, espaco: 1, descricao: '' },
  { id: 'pavio', nome: 'Pavio (10m)', categoria: 'ferramenta', precoMin: 10, precoMax: 15, espaco: 2, descricao: '' },
  { id: 'pe_de_cabra', nome: 'Pé de cabra', categoria: 'ferramenta', precoMin: 5, precoMax: 10, espaco: 1, descricao: '' },
  { id: 'pregos', nome: 'Pregos (20)', categoria: 'ferramenta', precoMin: 0.5, precoMax: 1, espaco: 1, descricao: 'Máximo 20 unidades por compra.', maximoPorPersonagem: 20 },
  { id: 'pederneira', nome: 'Pederneira', categoria: 'ferramenta', precoMin: 0.5, precoMax: 1, espaco: 0.5, descricao: '' },
  { id: 'picareta', nome: 'Picareta', categoria: 'ferramenta', precoMin: 10, precoMax: 25, espaco: 2, descricao: '' },
  { id: 'relogio_bolso', nome: 'Relógio de bolso', categoria: 'ferramenta', precoMin: 25, precoMax: 50, espaco: 0.5, descricao: '' },
  { id: 'sabao_barra_ferramenta', nome: 'Sabão (Barra)', categoria: 'ferramenta', precoMin: 0.25, precoMax: 0.5, espaco: 0, descricao: 'Máximo 2 barras.', maximoPorPersonagem: 2 },
  { id: 'saco_dormir', nome: 'Saco de dormir', categoria: 'ferramenta', precoMin: 0.25, precoMax: 0.5, espaco: 2, descricao: '' },
  { id: 'tamborim', nome: 'Tamborim', categoria: 'ferramenta', precoMin: 10, precoMax: 20, espaco: 1, descricao: '' },
  { id: 'vara_pescar', nome: 'Vara de pescar', categoria: 'ferramenta', precoMin: 3, precoMax: 5, espaco: 1, descricao: '' },
  { id: 'viola', nome: 'Viola', categoria: 'ferramenta', precoMin: 30, precoMax: 60, espaco: 1, descricao: '' },
  { id: 'violao', nome: 'Violão', categoria: 'ferramenta', precoMin: 30, precoMax: 60, espaco: 1, descricao: '' },
  { id: 'violino', nome: 'Violino', categoria: 'ferramenta', precoMin: 50, precoMax: 100, espaco: 1, descricao: '' },
  { id: 'zabumba', nome: 'Zabumba', categoria: 'ferramenta', precoMin: 30, precoMax: 50, espaco: 2, descricao: '' },
];

export const CATEGORIAS_COMPRAS = [
  { id: 'arma_fogo', label: 'Armas de Fogo' },
  { id: 'arma_branca', label: 'Armas Brancas' },
  { id: 'acessorio', label: 'Acessórios' },
  { id: 'municao', label: 'Munição' },
  { id: 'protecao', label: 'Proteção' },
  { id: 'comida', label: 'Mercearia' },
  { id: 'roupa', label: 'Roda da Moda' },
  { id: 'ferramenta', label: 'Ferramentas e Diversos' },
];

export function precoMedio(item) {
  if (item.precoMin == null || item.precoMax == null) return null;
  return (item.precoMin + item.precoMax) / 2;
}